"""Human-readable labels for application settings; unknown keys are preserved."""
GROUPS = {
    "retrieval": "记忆检索默认值（对话优先使用思考档位的预算）",
    "speaker": "不同说话人的记忆", "scoring": "记忆相关性与遗忘",
    "compression": "旧记忆整理", "privacy": "不保存的隐私内容",
    "tools": "文件与网络工具", "knowledge": "本地资料库",
    "live2d": "桌宠形象（保存后重启桌宠生效）", "update": "更新来源",
    "auto_rules": "自动选档规则", "ui": "思考面板",
}
LABELS = {
    "token_budget": "记忆字数预算（tokens）", "max_entries": "最多记忆条数",
    "recency_floor": "保留近期记忆条数", "min_score": "最低相关度",
    "owner_weight": "主人记忆权重", "guest_weight": "陌生人权重",
    "known_guest_weight": "已识别群友权重", "guest_max_importance": "陌生人重要度上限",
    "known_guest_max_importance": "群友重要度上限", "guest_decay": "陌生人遗忘系数",
    "known_guest_decay": "群友遗忘系数", "mark_in_context": "标明记忆说话人",
    "importance_floor": "最低重要度权重", "tag_bonus": "标签命中奖励",
    "permanent": "永久记忆", "slow": "缓慢遗忘", "normal": "普通遗忘",
    "daily_to_weekly_after_days": "日记整理为周摘要的天数",
    "weekly_to_monthly_after_days": "周摘要整理为月摘要的天数",
    "archive_originals": "整理后保留原始记忆", "blocked_patterns": "不保存的敏感词（每行一个）",
    "fs_root": "允许读写的文件夹", "search_backend": "普通搜索方式",
    "searxng_url": "SearXNG 地址", "proxy": "网络代理",
    "monthly_limit": "每月调用上限", "daily_limit": "每天调用上限",
    "timeout_seconds": "请求超时（秒）", "enabled": "启用",
    "general": "普通搜索缓存（秒）", "news": "新闻搜索缓存（秒）",
    "page": "网页缓存（秒）", "docs_dir": "资料目录",
    "chunk_size": "资料分块字数", "max_chunks": "每次最多引用块数",
    "model": "Live2D 模型文件", "width": "窗口宽度", "height": "窗口高度",
    "zoom": "模型缩放", "fps": "每秒帧数", "auto_blink": "自动眨眼",
    "auto_breath": "自动呼吸", "idle_group": "待机动作组",
    "animate_thinking": "用表情表现思考", "hover_feedback": "鼠标悬停反馈",
    "position": "面板位置", "offset": "面板间距", "auto_hide_seconds": "自动隐藏等待（秒）",
    "length_per_20_chars": "问题每增加 20 字的分数", "frugal": "省电分界", "daily": "日常分界",
    "serious": "认真分界", "deep": "深究分界", "question_words": "疑问词",
    "depth_words": "深入分析词", "simple_words": "简单问题词", "code_signals": "代码相关词",
    "thresholds": "分数分界", "signals": "问题特征", "tavily": "境外资料检索",
    "cache_ttl": "搜索缓存", "decay_lambda": "遗忘系数", "repo": "更新仓库",
}
CHOICES = {"tools.search_backend": [("普通搜索", "ddgs"), ("自建 SearXNG", "searxng")],
           "ui.position": [("右侧", "right"), ("左侧", "left"), ("上方", "top"), ("下方", "bottom")]}
